#!/usr/bin/python
import argparse, os, sys, ConfigParser

parser = argparse.ArgumentParser(description='show sugar activity name')
parser.add_argument('file', nargs='?', type=str, help='activity info file',
                        default='activity/activity.info')
args = parser.parse_args()

cp = ConfigParser.ConfigParser()
cp.read(args.file)
print cp.get('Activity', 'activity_version')
