#!/bin/sh

# Options
CHROOT="default"
MODULESET="sugar chat-activity"

SJH="SJH_DISTRIBUTION=olpc-3 HOME=/ /opt/sugar/sugar-jhbuild"
SNAPSHOT="sugar-snapshot-`date +%Y%m%d%H%M`.tar.bz2"

mock -r $CHROOT --init
mock -r $CHROOT --install yum git

mock -r $CHROOT --shell << EOF
cd /opt
git clone git://dev.laptop.org/sugar-jhbuild sugar

$SJH depscheck -s >/tmp/deps
EOF

mock -r $CHROOT --shell cat /tmp/deps | xargs mock -r $CHROOT --install

cat > /tmp/start-sugar << EOF
#!/bin/sh

if [ -f /etc/olpc-security ] ; then
  DBUS_CONFIG="--config-file /etc/dbus-1/session-olpc.conf"
fi

DBUS_LAUNCH="/usr/bin/dbus-launch --exit-with-session \$DBUS_CONFIG"
CK_LAUNCH="/usr/bin/ck-xinit-session"
SJH_RUN="/opt/sugar/sugar-jhbuild run"

exec \$SJH_RUN \$DBUS_LAUNCH \$CK_LAUNCH sugar
EOF

mock -r $CHROOT --copyin /tmp/start-sugar /tmp

mock -r $CHROOT --shell << EOF
$SJH --no-interact build $MODULESET

cp /tmp/start-sugar /opt/sugar/start
chmod +x /opt/sugar/start
rm -rf /opt/sugar/source
tar cvfPj $SNAPSHOT /opt/sugar
EOF

mock -r $CHROOT --copyout $SNAPSHOT .
